//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_TRANSACCIONES
    {
        public API_TRANSACCIONES()
        {
            this.API_TRANSICIONES = new HashSet<API_TRANSICIONES>();
        }
    
        public string TABLA { get; set; }
        public string TRANSACCION { get; set; }
        public string NOMBRE_LARGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string SENTENCIA { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual API_TABLAS API_TABLAS { get; set; }
        public virtual ICollection<API_TRANSICIONES> API_TRANSICIONES { get; set; }
    }
}
