//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORAS_DE_ERROR
    {
        public decimal SECUENCIAL { get; set; }
        public string TOKEN_ERROR { get; set; }
        public string MENSAJE_ERROR { get; set; }
        public string RASTREO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string FICHA { get; set; }
        public string GLOSA { get; set; }
    }
}
