//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CG_REF_CODES
    {
        public string RV_DOMAIN { get; set; }
        public string RV_LOW_VALUE { get; set; }
        public string RV_HIGH_VALUE { get; set; }
        public string RV_ABBREVIATION { get; set; }
        public string RV_MEANING { get; set; }
    }
}
