//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.ClientClaims = new HashSet<ClientClaims>();
            this.ClientCorsOrigins = new HashSet<ClientCorsOrigins>();
            this.ClientCustomGrantTypes = new HashSet<ClientCustomGrantTypes>();
            this.ClientIdPRestrictions = new HashSet<ClientIdPRestrictions>();
            this.ClientPostLogoutRedirectUris = new HashSet<ClientPostLogoutRedirectUris>();
            this.ClientRedirectUris = new HashSet<ClientRedirectUris>();
            this.ClientScopes = new HashSet<ClientScopes>();
            this.ClientSecrets = new HashSet<ClientSecrets>();
        }
    
        public int Id { get; set; }
        public short Enabled { get; set; }
        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientUri { get; set; }
        public string LogoUri { get; set; }
        public short RequireConsent { get; set; }
        public short AllowRememberConsent { get; set; }
        public short AllowAccessTokensViaBrowser { get; set; }
        public int Flow { get; set; }
        public short AllowClientCredentialsOnly { get; set; }
        public string LogoutUri { get; set; }
        public short LogoutSessionRequired { get; set; }
        public short RequireSignOutPrompt { get; set; }
        public short AllowAccessToAllScopes { get; set; }
        public int IdentityTokenLifetime { get; set; }
        public int AccessTokenLifetime { get; set; }
        public int AuthorizationCodeLifetime { get; set; }
        public int AbsoluteRefreshTokenLifetime { get; set; }
        public int SlidingRefreshTokenLifetime { get; set; }
        public int RefreshTokenUsage { get; set; }
        public short UpdateAccessTokenOnRefresh { get; set; }
        public int RefreshTokenExpiration { get; set; }
        public int AccessTokenType { get; set; }
        public short EnableLocalLogin { get; set; }
        public short IncludeJwtId { get; set; }
        public short AlwaysSendClientClaims { get; set; }
        public short PrefixClientClaims { get; set; }
        public short AllowAccessToAllGrantTypes { get; set; }
    
        public virtual ICollection<ClientClaims> ClientClaims { get; set; }
        public virtual ICollection<ClientCorsOrigins> ClientCorsOrigins { get; set; }
        public virtual ICollection<ClientCustomGrantTypes> ClientCustomGrantTypes { get; set; }
        public virtual ICollection<ClientIdPRestrictions> ClientIdPRestrictions { get; set; }
        public virtual ICollection<ClientPostLogoutRedirectUris> ClientPostLogoutRedirectUris { get; set; }
        public virtual ICollection<ClientRedirectUris> ClientRedirectUris { get; set; }
        public virtual ICollection<ClientScopes> ClientScopes { get; set; }
        public virtual ICollection<ClientSecrets> ClientSecrets { get; set; }
    }
}
