//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDM_SISTEMAS
    {
        public IDM_SISTEMAS()
        {
            this.IDM_FICHAS_SIS = new HashSet<IDM_FICHAS_SIS>();
            this.IDM_SISTEMAS_CLIENTESTS = new HashSet<IDM_SISTEMAS_CLIENTESTS>();
            this.IDM_USUARIOS_REL = new HashSet<IDM_USUARIOS_REL>();
        }
    
        public decimal SISTEMA_ID { get; set; }
        public string DESC_SISTEMA { get; set; }
        public string SIGLAS_SISTEMA { get; set; }
        public System.DateTime FECHA_ELABORACION { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string TOOLTIP { get; set; }
        public string COLOR { get; set; }
        public string ICONO { get; set; }
        public string URL { get; set; }
        public string TAMANO { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public string CLASE { get; set; }
        public string VALOR1 { get; set; }
        public string VALOR2 { get; set; }
        public string VALOR3 { get; set; }
        public string IMAGEN { get; set; }
    
        public virtual ICollection<IDM_FICHAS_SIS> IDM_FICHAS_SIS { get; set; }
        public virtual ICollection<IDM_SISTEMAS_CLIENTESTS> IDM_SISTEMAS_CLIENTESTS { get; set; }
        public virtual ICollection<IDM_USUARIOS_REL> IDM_USUARIOS_REL { get; set; }
    }
}
