//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDM_USUARIOS
    {
        public IDM_USUARIOS()
        {
            this.IDM_FICHAS_REG = new HashSet<IDM_FICHAS_REG>();
            this.IDM_USUARIOS_REL = new HashSet<IDM_USUARIOS_REL>();
            this.IDM_USUARIOS_RESTRICCIONES = new HashSet<IDM_USUARIOS_RESTRICCIONES>();
        }
    
        public decimal USUARIO_ID { get; set; }
        public System.DateTime FECHA_ELABORACION { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string NICK_USUARIO { get; set; }
        public string TIPO_USUARIO_ID { get; set; }
        public Nullable<decimal> NIVEL_USUARIO_ID { get; set; }
        public Nullable<decimal> PERSONA_ID { get; set; }
        public string PUESTO { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<IDM_FICHAS_REG> IDM_FICHAS_REG { get; set; }
        public virtual IDM_PERSONAS IDM_PERSONAS { get; set; }
        public virtual ICollection<IDM_USUARIOS_REL> IDM_USUARIOS_REL { get; set; }
        public virtual ICollection<IDM_USUARIOS_RESTRICCIONES> IDM_USUARIOS_RESTRICCIONES { get; set; }
        public virtual IDM_USUARIOS_NIV IDM_USUARIOS_NIV { get; set; }
        public virtual IDM_USUARIOS_TIPOS IDM_USUARIOS_TIPOS { get; set; }
    }
}
