//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDM_CRIPTOGRAFIAS
    {
        public short GESTION { get; set; }
        public decimal CRIPTO_ID { get; set; }
        public decimal SISTEMA_ID { get; set; }
        public string CVV_LLAVE { get; set; }
        public string CVV_VECTOR { get; set; }
        public string CVV_CODIGO { get; set; }
        public string CVV_CRIPTO { get; set; }
        public decimal HASH_KEY { get; set; }
        public string HASH_DIGEST { get; set; }
        public System.DateTime FECHA_CRIPTO { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    }
}
