//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDM_USUARIOS_TIPOS
    {
        public IDM_USUARIOS_TIPOS()
        {
            this.IDM_USUARIOS = new HashSet<IDM_USUARIOS>();
        }
    
        public string TIPO_USUARIO_ID { get; set; }
        public string DESC_TIPO_USUARIO { get; set; }
        public string SIGLAS_TIPO_USUARIO { get; set; }
        public System.DateTime FECHA_ELABORACION { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<IDM_USUARIOS> IDM_USUARIOS { get; set; }
    }
}
