//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDM_CORREO_ENVIOS
    {
        public long ID_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public string DESC_ENVIO { get; set; }
        public string DE_CORREO { get; set; }
        public string DE_NOMBRE { get; set; }
        public string PARA_CORREO { get; set; }
        public string PARA_NOMBRE { get; set; }
        public string TAREA { get; set; }
        public string ASUNTO { get; set; }
        public string ATRIBUTO { get; set; }
        public string CUERPO { get; set; }
        public string BITACORA { get; set; }
        public string TEXTO_HTML { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public Nullable<System.DateTime> FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    }
}
