//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDM_TIPO_TRANSACCION_STMT
    {
        public decimal TIPO_TRANSACCION_ID { get; set; }
        public string TIPO_SENTENCIA { get; set; }
        public string SQL_SENTENCIA { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public string FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public string FEC_MOD { get; set; }
    
        public virtual IDM_TRANSACCIONES_TIPOS IDM_TRANSACCIONES_TIPOS { get; set; }
    }
}
