//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJES_DE_ERROR
    {
        public string TIPO_MENSAJE_ERROR { get; set; }
        public short CODIGO_MENSAJE_ERROR { get; set; }
        public string TEXTO { get; set; }
        public string ORIGEN { get; set; }
        public string CAUSA { get; set; }
        public string ACCION { get; set; }
        public string COMENTARIO { get; set; }
    }
}
