//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities(string dName) : base("name=" + dName) { }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            //var props = new Entities().GetType().GetProperties(BindingFlags.DeclaredOnly |
            //                             BindingFlags.Public |
            //                             BindingFlags.Instance);
            //foreach (var item in props)
            //{
            //    string assemblyName = "SAS.TOOLS.DA."+item.Name+",SAS.TOOLS.DA"; 
            //    var classType = new Type[] { Type.GetType(assemblyName)};
            //    var method = modelBuilder.GetType().GetMethod("Entity");
            //    var genericMethod = method.MakeGenericMethod(classType);
            //    object entTypConfig = genericMethod.Invoke(modelBuilder, null);
            //    var getToTable = entTypConfig.GetType().GetMethod("ToTable", new[] { typeof(string) });
            //    getToTable.Invoke(entTypConfig, new object[] { item.Name });
            //}
            //base.OnModelCreating(modelBuilder);

        }

        public DbSet<SAS_ACCIONES> SAS_ACCIONES { get; set; }
        public DbSet<SAS_DICCIONARIO_ETAPAS> SAS_DICCIONARIO_ETAPAS { get; set; }
        public DbSet<SAS_DICCIONARIO_FILTROS> SAS_DICCIONARIO_FILTROS { get; set; }
        public DbSet<SAS_DICCIONARIO_OPERADORES> SAS_DICCIONARIO_OPERADORES { get; set; }
        public DbSet<SAS_FLUJOS> SAS_FLUJOS { get; set; }
        public DbSet<SAS_FLUJOS_OPE_ACCIONES> SAS_FLUJOS_OPE_ACCIONES { get; set; }
        public DbSet<SAS_FLUJOS_OPERACION> SAS_FLUJOS_OPERACION { get; set; }
        public DbSet<SAS_MENUS> SAS_MENUS { get; set; }
        public DbSet<SAS_PERFIL_FLUJO_OPE> SAS_PERFIL_FLUJO_OPE { get; set; }
        public DbSet<SAS_PERFIL_MENU> SAS_PERFIL_MENU { get; set; }
        public DbSet<SAS_PERFILES> SAS_PERFILES { get; set; }
        public DbSet<SAS_TABLAS> SAS_TABLAS { get; set; }
        public DbSet<SAS_TABLAS_COLUMNAS> SAS_TABLAS_COLUMNAS { get; set; }
        public DbSet<SAS_TABLAS_FILTROS> SAS_TABLAS_FILTROS { get; set; }
        public DbSet<SAS_SISTEMAS> SAS_SISTEMAS { get; set; }
        public DbSet<SAS_ACCESOS_GRUPOS> SAS_ACCESOS_GRUPOS { get; set; }
        public DbSet<SAS_ACCESOS_PERFILES> SAS_ACCESOS_PERFILES { get; set; }
        public DbSet<SAS_GRUPO_FILTRO> SAS_GRUPO_FILTRO { get; set; }
        public DbSet<SAS_GRUPO_PREDICADO> SAS_GRUPO_PREDICADO { get; set; }
        public DbSet<MENSAJES_DE_ERROR> MENSAJES_DE_ERROR { get; set; }
        public DbSet<SAS_CONDICIONES> SAS_CONDICIONES { get; set; }
        public DbSet<SAS_CORREO_ENVIADOS> SAS_CORREO_ENVIADOS { get; set; }
        public DbSet<SAS_CORREO_ENVIOS> SAS_CORREO_ENVIOS { get; set; }
        public DbSet<SAS_CORREO_FORMATO> SAS_CORREO_FORMATO { get; set; }
        public DbSet<SAS_CORREO_REMITENTES> SAS_CORREO_REMITENTES { get; set; }
        public DbSet<SAS_DOC_AUDITORIA> SAS_DOC_AUDITORIA { get; set; }
        public DbSet<SAS_DOC_CABECERA> SAS_DOC_CABECERA { get; set; }
        public DbSet<SAS_DOCGRP_GRUPO> SAS_DOCGRP_GRUPO { get; set; }
        public DbSet<SAS_DOCGRP_PREDICADO> SAS_DOCGRP_PREDICADO { get; set; }
        public DbSet<SAS_DOCMEN_MENU> SAS_DOCMEN_MENU { get; set; }
        public DbSet<SAS_DOCPER_PERFIL> SAS_DOCPER_PERFIL { get; set; }
        public DbSet<SAS_DOCPER_PERFIL_FLUOPE> SAS_DOCPER_PERFIL_FLUOPE { get; set; }
        public DbSet<SAS_DOCPER_PERFIL_MENU> SAS_DOCPER_PERFIL_MENU { get; set; }
        public DbSet<SAS_FLUJOS_OPE_GRUPO> SAS_FLUJOS_OPE_GRUPO { get; set; }
        public DbSet<SAS_FLUJOS_OPE_REGLA> SAS_FLUJOS_OPE_REGLA { get; set; }
        public DbSet<SAS_FLUJOS_TABLAS> SAS_FLUJOS_TABLAS { get; set; }
        public DbSet<SAS_PARAMETROS> SAS_PARAMETROS { get; set; }
        public DbSet<SAS_REGLAS> SAS_REGLAS { get; set; }
        public DbSet<SAS_REGLAS_CONDICIONES> SAS_REGLAS_CONDICIONES { get; set; }
        public DbSet<SAS_SISTEMAS_APLICACION> SAS_SISTEMAS_APLICACION { get; set; }
        public DbSet<SAS_SISTEMAS_ETAPAS> SAS_SISTEMAS_ETAPAS { get; set; }
        public DbSet<SAS_SISTEMAS_PARAMETROS> SAS_SISTEMAS_PARAMETROS { get; set; }
        public DbSet<SAS_SOLICITUD_USUARIO> SAS_SOLICITUD_USUARIO { get; set; }
        public DbSet<SAS_SOLUSR_AUDITORIA> SAS_SOLUSR_AUDITORIA { get; set; }
        public DbSet<SAS_SOLUSR_PERFIL> SAS_SOLUSR_PERFIL { get; set; }
        public DbSet<SAS_SOLUSR_PERFIL_GRUPO> SAS_SOLUSR_PERFIL_GRUPO { get; set; }
        public DbSet<SAS_USUARIOS> SAS_USUARIOS { get; set; }
        public DbSet<SAS_USUARIOS_BLOQUEO> SAS_USUARIOS_BLOQUEO { get; set; }
        public DbSet<SAS_USUARIOS_INFORMACION> SAS_USUARIOS_INFORMACION { get; set; }
        public DbSet<SAS_USUARIOS_PARAMETROS> SAS_USUARIOS_PARAMETROS { get; set; }
        public DbSet<CG_REF_CODES> CG_REF_CODES { get; set; }
        public DbSet<X_SAS_MENUS> X_SAS_MENUS { get; set; }
    }
}
