//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_DOC_CABECERA
    {
        public SAS_DOC_CABECERA()
        {
            this.SAS_DOC_AUDITORIA = new HashSet<SAS_DOC_AUDITORIA>();
            this.SAS_DOCGRP_GRUPO = new HashSet<SAS_DOCGRP_GRUPO>();
            this.SAS_DOCMEN_MENU = new HashSet<SAS_DOCMEN_MENU>();
            this.SAS_DOCPER_PERFIL = new HashSet<SAS_DOCPER_PERFIL>();
        }
    
        public int ID_SISTEMA { get; set; }
        public int NRO_DOCUMENTO { get; set; }
        public System.DateTime FECHA_ELABORACION { get; set; }
        public string TIPO_OPERACION { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string RESUMEN_OPERACION { get; set; }
        public string USUARIO_VERIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_VERIFICACION { get; set; }
        public string USUARIO_APROBACION { get; set; }
        public Nullable<System.DateTime> FECHA_APROBACION { get; set; }
    
        public virtual ICollection<SAS_DOC_AUDITORIA> SAS_DOC_AUDITORIA { get; set; }
        public virtual ICollection<SAS_DOCGRP_GRUPO> SAS_DOCGRP_GRUPO { get; set; }
        public virtual ICollection<SAS_DOCMEN_MENU> SAS_DOCMEN_MENU { get; set; }
        public virtual ICollection<SAS_DOCPER_PERFIL> SAS_DOCPER_PERFIL { get; set; }
    }
}
