//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_ACCESOS_PERFILES
    {
        public SAS_ACCESOS_PERFILES()
        {
            this.SAS_ACCESOS_GRUPOS = new HashSet<SAS_ACCESOS_GRUPOS>();
        }
    
        public int ID_ACCESO { get; set; }
        public int ID_SISTEMA { get; set; }
        public int ID_PERFIL { get; set; }
        public string USUARIO { get; set; }
        public string POR_DEFECTO { get; set; }
        public string RESTRICCION { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<SAS_ACCESOS_GRUPOS> SAS_ACCESOS_GRUPOS { get; set; }
        public virtual SAS_PERFILES SAS_PERFILES { get; set; }
        public virtual SAS_SISTEMAS SAS_SISTEMAS { get; set; }
        public virtual SAS_USUARIOS SAS_USUARIOS { get; set; }
    }
}
