//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_MENUS
    {
        public SAS_MENUS()
        {
            this.SAS_PERFIL_MENU = new HashSet<SAS_PERFIL_MENU>();
            this.SAS_DOCPER_PERFIL_MENU = new HashSet<SAS_DOCPER_PERFIL_MENU>();
        }
    
        public int ID_MENU { get; set; }
        public int ID_SISTEMA { get; set; }
        public string NOMBRE_MENU { get; set; }
        public int ID_MENU_PADRE { get; set; }
        public short ORDEN { get; set; }
        public string JERARQUIA { get; set; }
        public string METODO { get; set; }
        public string DESC_MENU { get; set; }
        public string TIPO_MENU { get; set; }
        public string ICO_MENU { get; set; }
        public string TOOLTIP { get; set; }
        public string VIGENTE { get; set; }
        public string HABILITADO { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual ICollection<SAS_PERFIL_MENU> SAS_PERFIL_MENU { get; set; }
        public virtual SAS_SISTEMAS SAS_SISTEMAS { get; set; }
        public virtual ICollection<SAS_DOCPER_PERFIL_MENU> SAS_DOCPER_PERFIL_MENU { get; set; }
    }
}
