//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_TABLAS_COLUMNAS
    {
        public SAS_TABLAS_COLUMNAS()
        {
            this.SAS_TABLAS_FILTROS = new HashSet<SAS_TABLAS_FILTROS>();
        }
    
        public int ID_SISTEMA { get; set; }
        public int ID_TABLA { get; set; }
        public int ID_COLUMNA { get; set; }
        public string NOMBRE_COLUMNA { get; set; }
        public string COMENTARIO { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual SAS_TABLAS SAS_TABLAS { get; set; }
        public virtual ICollection<SAS_TABLAS_FILTROS> SAS_TABLAS_FILTROS { get; set; }
    }
}
