//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_GRUPO_FILTRO
    {
        public SAS_GRUPO_FILTRO()
        {
            this.SAS_GRUPO_PREDICADO = new HashSet<SAS_GRUPO_PREDICADO>();
            this.SAS_FLUJOS_OPE_GRUPO = new HashSet<SAS_FLUJOS_OPE_GRUPO>();
        }
    
        public int ID_GRUPO { get; set; }
        public int ID_SISTEMA { get; set; }
        public string NOMBRE_GRUPO { get; set; }
        public string DESC_GRUPO { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual SAS_SISTEMAS SAS_SISTEMAS { get; set; }
        public virtual ICollection<SAS_GRUPO_PREDICADO> SAS_GRUPO_PREDICADO { get; set; }
        public virtual ICollection<SAS_FLUJOS_OPE_GRUPO> SAS_FLUJOS_OPE_GRUPO { get; set; }
    }
}
