//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_FLUJOS_OPERACION
    {
        public SAS_FLUJOS_OPERACION()
        {
            this.SAS_FLUJOS_OPE_ACCIONES = new HashSet<SAS_FLUJOS_OPE_ACCIONES>();
            this.SAS_PERFIL_FLUJO_OPE = new HashSet<SAS_PERFIL_FLUJO_OPE>();
            this.SAS_DOCPER_PERFIL_FLUOPE = new HashSet<SAS_DOCPER_PERFIL_FLUOPE>();
            this.SAS_FLUJOS_OPE_GRUPO = new HashSet<SAS_FLUJOS_OPE_GRUPO>();
            this.SAS_FLUJOS_OPE_REGLA = new HashSet<SAS_FLUJOS_OPE_REGLA>();
        }
    
        public int ID_FLUJO { get; set; }
        public int ID_OPERACION { get; set; }
        public string DESC_OPERACION { get; set; }
        public string VIGENTE { get; set; }
        public string API_ESTADO { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual SAS_FLUJOS SAS_FLUJOS { get; set; }
        public virtual ICollection<SAS_FLUJOS_OPE_ACCIONES> SAS_FLUJOS_OPE_ACCIONES { get; set; }
        public virtual ICollection<SAS_PERFIL_FLUJO_OPE> SAS_PERFIL_FLUJO_OPE { get; set; }
        public virtual ICollection<SAS_DOCPER_PERFIL_FLUOPE> SAS_DOCPER_PERFIL_FLUOPE { get; set; }
        public virtual ICollection<SAS_FLUJOS_OPE_GRUPO> SAS_FLUJOS_OPE_GRUPO { get; set; }
        public virtual ICollection<SAS_FLUJOS_OPE_REGLA> SAS_FLUJOS_OPE_REGLA { get; set; }
    }
}
