//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAS_DOC_AUDITORIA
    {
        public int NRO_DOCUMENTO { get; set; }
        public int SECUENCIA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string USUARIO { get; set; }
        public string API_ESTADO { get; set; }
        public string ESTADO_DESDE { get; set; }
        public string TRANSACCION { get; set; }
        public string ESTADO_HASTA { get; set; }
        public string API_TRANSACCION { get; set; }
        public string USU_CRE { get; set; }
        public System.DateTime FEC_CRE { get; set; }
        public string USU_MOD { get; set; }
        public Nullable<System.DateTime> FEC_MOD { get; set; }
    
        public virtual SAS_DOC_CABECERA SAS_DOC_CABECERA { get; set; }
    }
}
