//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scopes
    {
        public Scopes()
        {
            this.ScopeClaims = new HashSet<ScopeClaims>();
            this.ScopeSecrets = new HashSet<ScopeSecrets>();
        }
    
        public int Id { get; set; }
        public short Enabled { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public short Required { get; set; }
        public short Emphasize { get; set; }
        public int Type { get; set; }
        public short IncludeAllClaimsForUser { get; set; }
        public string ClaimsRule { get; set; }
        public short ShowInDiscoveryDocument { get; set; }
        public short AllowUnrestrictedIntrospection { get; set; }
    
        public virtual ICollection<ScopeClaims> ScopeClaims { get; set; }
        public virtual ICollection<ScopeSecrets> ScopeSecrets { get; set; }
    }
}
