//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeSecrets
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTimeOffset> Expiration { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public int Scope_Id { get; set; }
    
        public virtual Scopes Scopes { get; set; }
    }
}
