//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tokens
    {
        public string Key { get; set; }
        public short TokenType { get; set; }
        public string SubjectId { get; set; }
        public string ClientId { get; set; }
        public string JsonCode { get; set; }
        public System.DateTimeOffset Expiry { get; set; }
    }
}
