//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.TOOLS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_IDM_LOVGRAL
    {
        public string PK { get; set; }
        public decimal LLAVE { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
        public string CLASIFICADOR { get; set; }
    }
}
